services:
  scylladb:
    image: scylladb/scylla:latest
    container_name: weaponmail-db
    ports:
      - "9042:9042" # Native protocol port (for Java driver)
      - "2042:2042" # Thrift port
    volumes:
      - ./data/scylla:/var/lib/scylla
    command: --smp 1 --memory 1G --overprovisioned 1 --developer-mode 1

  # Optional: A web UI to look at your data
  scylla-dashboard:
    image: scylladb/scylla-manager:latest
    container_name: weaponmail-db-manager
    depends_on:
      - scylladb
