spring:
  cassandra:
    keyspace-name: ${CASSANDRA_KEYSPACE:weaponmail}
    contact-points:
      - ${CASSANDRA_HOST:scylladb}:${CASSANDRA_PORT:9042}
    local-datacenter: ${CASSANDRA_DATACENTER:datacenter1}
    schema-action: create_if_not_exists
    request:
      timeout: 10s
    connection:
      connect-timeout: 10s
      init-query-timeout: 10s